---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: ckad
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce  # allow mount (as read write ) on a single node.
  hostPath:
    path: /data/db
