---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: ckad
  labels:
    tier: frontend
    team: artemidis
  annotations:
    deployer: medkha
spec:
  containers:
    - image: nginx:1.25.1
      name: pod-1
