---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ckad
spec:
  volumes:
    - name: logs-db
      persistentVolumeClaim:
        claimName: logs-pvc
  containers:
    - image: nginx:1.25.1
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-db
