---
apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  namespace: ckad
spec:
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    - image: alpine:3.12.0
      args:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "container one: $(date)"
            sleep 10
          done
      name: one
      volumeMounts:
        - name: shared
          mountPath: /etc/a
    - image: alpine:3.12.0
      args:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "container one: $(date)"
            sleep 10
          done
      name: two
      volumeMounts:
        - name: shared
          mountPath: /etc/b
