---
apiVersion: batch/v1
kind: Job
metadata:
  name: random-hash
  namespace: ckad
spec:
  parallelism: 2
  completions: 5
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - $RANDOM | base64 | head -c 20
        image: alpine:3.17.3
        name: random-hash
      restartPolicy: Never
