---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ckad
spec:
  containers:
    - image: nginx:1.17.0
      name: nginx
      ports:
        - containerPort: 80
      env:
        - name: DB_URL
          value: postgresql://mydb:5432
        - name: DB_USER_NAME
          value: admin
